name: ythumbnail
version: 1.1.0+2
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  get: 4.6.6
  icons_launcher: ^2.1.7
  image: ^4.1.7
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  screenshot: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: ytThumbnail
  logo_path: assets\yt.png
  msix_version: 1.1.0.0
