name: ythumbnail
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.6
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  screenshot: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
