on:
  push:
    branches:
      - master

name: "Build MSIX & Release"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: dart fix --apply
      - run: dart run msix:create

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/x64/runner/Release/ythumbnail.msix"
          tag: v1.2.0+${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
