on:
  push:
    branches:
      - master

name: "Windows Release"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      # - run: dart fix --apply
      - run: get-content pubspec.yaml | %{$_ -replace "XXX","${{ secrets.ACCESS_TOKEN }}"} | Set-Content pubspec.sed
      - run: cp pubspec.sed pubspec.yaml
      - run: flutter pub get
      # - run: flutter build windows --release
      - run: dart run msix:create

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/windows/x64/runner/Release/ythumbnail.msix"
          tag: v1.2.0+${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
